### PR TITLE
Chore: Extend the test for the SmartInputField to cover clicks, too

### PR DESCRIPTION
**Pull request by fgehring**

### CODE REVIEW

**Review by depoulo — APPROVED** [review]

**Comment by fgehring** [comment]
@depoulo Please delete the branch after merging. Thanks.

**Comment by depoulo** [comment]
@fgehring I would, but I couldn't, since I don't have push access to your fork.

**Comment by fgehring** [comment]
@depoulo Ahh, I see.
But I can't add a team neither. Don't know why.
Maybe because it's a public repository?

**Comment by depoulo** [comment]
Yeah you'd have to add me as a collaborator personally. Or just take care of deleting your own branches. In open source, that's the standard I guess and makes very much sense.
It's just a nice to have thing in a closed source environment that you give all of your peers full access to your forks using GitHub teams.

**Pull request merged**
