### PR TITLE
New: Add blur option for SmartInputField

### PR DESCRIPTION
**Pull request by fgehring**
UNITY-5222

### CODE REVIEW

**Comment by depoulo** [comment]
There is this:

https://github.com/ePages-de/react-components/blob/38d69002e8a368d5701123a341c029764d97b9c4/src/form/SmartInputField.jsx#L140

So if all you want is to style a sibling of the SmartInputField depending on whether the SmartInputField is focused, you should be able to do so with CSS only (unless CSS modules get in your way).

**Comment by depoulo** [comment]
If that isn't possible, I'm fine with your addition, just make sure to cover the things you added with tests, and, first off, to fix the failure (npm test gives me this:)

```
 FAIL  test/form/SmartInputField.spec.jsx (10.159s)
  ● SmartInputField › focuses and blurs

    Error: Uncaught [TypeError: onBlur is not a function]
```

**Comment by fgehring** [comment]
> There is this:
> 
> [react-components/src/form/SmartInputField.jsx](https://github.com/ePages-de/react-components/blob/38d69002e8a368d5701123a341c029764d97b9c4/src/form/SmartInputField.jsx#L140)
> 
> Line 140 in [38d6900](/ePages-de/react-components/commit/38d69002e8a368d5701123a341c029764d97b9c4)
> 
>  focused && styles.baseFocused, 
> So if all you want is to style a sibling of the SmartInputField depending on whether the SmartInputField is focused, you should be able to do so with CSS only (unless CSS modules get in your way).

But we do not just want to know if it is focussed but furthermore how many elements are displayed.

**Comment by fgehring** [comment]
> If that isn't possible, I'm fine with your addition, just make sure to cover the things you added with tests, and, first off, to fix the failure (npm test gives me this:)
> 
> ```
>  FAIL  test/form/SmartInputField.spec.jsx (10.159s)
>   ● SmartInputField › focuses and blurs
> 
>     Error: Uncaught [TypeError: onBlur is not a function]
> ```

We will do, but first we need to confirm that this solution will work as we want. (This PR was not made to be merged immediately but just to show you what we want to do.)

**Comment by depoulo** [comment]
> But we do not just want to know if it is focussed but furthermore how many elements are displayed.

And how does your code change help with that? I got the impression we should have a quick phone call...

**Review by depoulo — APPROVED** [review]

**Comment by depoulo** [comment]
Merged and published as v0.8.0.

**Pull request closed without merging**
